import type { Config } from "tailwindcss";

export default {
	darkMode: ["class"],
	content: [
		"./pages/**/*.{js,ts,jsx,tsx,mdx}",
		"./components/**/*.{js,ts,jsx,tsx,mdx}",
		"./app/**/*.{js,ts,jsx,tsx,mdx}",
	],
	theme: {
		extend: {
			container: {
				center: true,
				padding: "2rem",
				screens: {
					sm: "640px",
					md: "768px",
					lg: "1024px",
					xl: "1280px",
					"2xl": "1600px",
				},
			},
			screens: {
				sm: "640px",
				md: "768px",
				lg: "1024px",
				xl: "1280px",
				"2xl": "1600px",
			},
			colors: {
				background: "hsl(var(--background))",
				foreground: "hsl(var(--foreground))",
				card: "hsl(var(--card))",
				cardForeground: "hsl(var(--card-foreground))",
				popover: "hsl(var(--popover))",
				popoverForeground: "hsl(var(--popover-foreground))",
				primary: "hsl(var(--primary))",
				primaryForeground: "hsl(var(--primary-foreground))",
				secondary: "hsl(var(--secondary))",
				secondaryForeground: "hsl(var(--secondary-foreground))",
				muted: "hsl(var(--muted))",
				mutedForeground: "hsl(var(--muted-foreground))",
				accent: "hsl(var(--accent))",
				accentForeground: "hsl(var(--accent-foreground))",
				destructive: "hsl(var(--destructive))",
				destructiveForeground: "hsl(var(--destructive-foreground))",
				border: "hsl(var(--border))",
				input: "hsl(var(--input))",
				ring: "hsl(var(--ring))",
				chart1: "hsl(var(--chart-1))",
				chart2: "hsl(var(--chart-2))",
				chart3: "hsl(var(--chart-3))",
				chart4: "hsl(var(--chart-4))",
				chart5: "hsl(var(--chart-5))",
				sidebar: {
					background: "hsl(var(--sidebar-background))",
					foreground: "hsl(var(--sidebar-foreground))",
					primary: "hsl(var(--sidebar-primary))",
					primaryForeground: "hsl(var(--sidebar-primary-foreground))",
					accent: "hsl(var(--sidebar-accent))",
					accentForeground: "hsl(var(--sidebar-accent-foreground))",
					border: "hsl(var(--sidebar-border))",
					ring: "hsl(var(--sidebar-ring))",
					DEFAULT: "hsl(var(--sidebar-background))",
					"primary-foreground": "hsl(var(--sidebar-primary-foreground))",
					"accent-foreground": "hsl(var(--sidebar-accent-foreground))",
				},
			},
			fontSize: {
				title: "4.5rem",
				subtitle: "2.5rem",
				alternative: "2rem",
				description: "1.5rem",
				min: "1.3rem",
				light: "1rem",
				minlight: "0.8rem",
			},
			borderRadius: {
				lg: "var(--radius)",
				md: "calc(var(--radius) - 2px)",
				sm: "calc(var(--radius) - 4px)",
			},
		},
	},
	plugins: [require("tailwindcss-animate")],
} satisfies Config;
